### ISSUE TITLE
Add Official Commands Framework.

### ISSUE THREAD

**Issue by EnokiUN** [EnokiUN/voltage#10]
A commands framwork is already present in RedCrewmate's [source code](https://github.com/enokiun/redcrewmatw)

Just finish plugins and add it to the main lib as so possibly:

```py
import voltage
from voltage.plugins import Commands

client = voltage.Client().plug(Commands("prefix"))

@client.command()
async def ping(ctx):
    await ctx.reply("Pong!")

client.run("token")
```

**Comment by EnokiUN** [comment]
This aged like milk I suppose :trollface:

**Comment by EnokiUN** [comment]
I'll close this after v1.0 I think I suppose

**Comment by EnokiUN** [comment]
@b1ue64 petition to close this

**Comment by EnokiUN** [comment]
nvm

**Comment by ksIsCute** [comment]
petition to petition

**Comment by ksIsCute** [comment]
lets go
