### ISSUE TITLE
add `member.add_role()`

### ISSUE THREAD

**Issue by EnokiUN** [EnokiUN/voltage#16]
### Summary

add `member.add_role()`

### What is the feature request for?

The core library

### The Problem

there is no `member.add_role()`

### The Ideal Solution

add `member.add_role()`

### The Current Solution

suffering

**Comment by EnokiUN** [comment]
:trollface:

**Comment by ksIsCute** [comment]
please also add remove_role
and also make an iterable to go through every role a user has

**Comment by EnokiUN** [comment]
user.roles exists
