### ISSUE TITLE
get user information, status, and presence to display

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#19]
### Summary

Get some basic user info (for a userinfo command)

### What is the feature request for?

The core library

### The Problem

get user information, status, and presence to display. The information i think is already a thing but I couldnt find it in the docs. Status is just the users active status. Return a boolean if there is none, basic stuffs. Then presence is "online", "idle", "invisible" (could add alias as offline) and "dnd" (because discord.py yes)

### The Ideal Solution

idk ur the nerds

**Comment by EnokiUN** [comment]
is `user.status` not working?

**Comment by ksIsCute** [comment]
honestly more concerned about the information and presence
but ill try it in a bit and see because your docs are dead

**Comment by EnokiUN** [comment]
wdym docs are dead?

**Comment by EnokiUN** [comment]
user.status works fine for me
