### ISSUE TITLE
add media alias

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#20]
### Summary

add media alias

### What is the feature request for?

Utilities

### The Problem

media is hard to rember

### The Ideal Solution

add media aliases like url, iconurl, icon_url, and more if i think of it

**Comment by EnokiUN** [comment]
that's how the revolt api works and it is the most correct thing to name it, url is already used for the title url and others don't make sense so I'll have to say no

**Comment by ksIsCute** [comment]
what about image
