### ISSUE TITLE
add color as colour

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#21]
### Summary

make color also be colour

### What is the feature request for?

The core library

### The Problem

habit writing color

### The Ideal Solution

add alias

**Comment by RGBCube** [comment]
no

**Comment by EnokiUN** [comment]
Revolt is originally British so using colour *is* more correct but since I hate when css fucks me up because "It's color you idiot" I'll look into it

**Comment by ksIsCute** [comment]
ok epi
