### ISSUE TITLE
fix documentation

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#22]
### Summary

fix documentation

### Reproduction Steps

went to the documentation

### Expected Results

show a page for the docs

### Actual Results

![this](https://i.imgur.com/WoiPPUF.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by EnokiUN** [comment]
it's not voltage, it's revolt-voltage because voltage was taken, the badge in the readme redirects to it.

**Comment by ksIsCute** [comment]
can you change it on the pypi?

**Comment by EnokiUN** [comment]
I've made a commit, it's gonna be fixed once I update the pypi version

**Comment by ksIsCute** [comment]
ok epic thank
