### ISSUE TITLE
allow creation of categories

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#24]
### Summary

allow creation of categories

### What is the feature request for?

The core library

### The Problem

create categories that you can put channels in

### The Ideal Solution

create categories

**Comment by EnokiUN** [comment]
smfhfijebd

**Comment by EnokiUN** [comment]
ignore that I suppose.

**Comment by EnokiUN** [comment]
If anyone knows how to make a category via the revolt api please lmk so I can implement it I suppose.
