### ISSUE TITLE
creation of roles, channels, categories, voice channels, etc.

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#25]
### Summary

creation of roles, channels, categories, voice channels, etc.

### What is the feature request for?

Utilities

### The Problem

creation of roles, channels, categories, voice channels, etc.

### The Ideal Solution

creating channels and roles and other shit with names, ranks, and role colors of choice (and maybe channel icon image)

**Comment by RGBCube** [comment]
`Guild.create_role`

**Comment by ksIsCute** [comment]
> `Guild.create_role`

you mean server. right?
