### ISSUE TITLE
client.servers error

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#26]
### Summary

len(client.servers) doesnt get servers added to if in the same session

### Reproduction Steps

use len(client.servers) and invite it (your bot) to a server and it wont update

### Expected Results

show

### Actual Results

didnt update members or servers

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EnokiUN** [comment]
yes there's already an open issue, check #18
