### ISSUE TITLE
permission check decorator

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#27]
### Summary

permission check decorator

### What is the feature request for?

The core library

### The Problem

so i dont have to suffer

### The Ideal Solution

@commands.has_permissions() OR @user.has_permissions() 
its easy to rember and im preeeeeeeeeeeeeeeeeety sure easy to create

### The Current Solution

alot of if statements

**Comment by EnokiUN** [comment]
As I've already stated that will get added when commands actually get merged into the core lib.

for now you can use the permissions attr to check permissions which is what I'd recommend doing anyway.
