### ISSUE TITLE
add default embed content

### ISSUE THREAD

**Issue by ksIsCute** [EnokiUN/voltage#48]
### Summary

just change default embed content so it looks like it only sends the embed with no text above

### What is the feature request for?

Utilities

### The Problem

it makes it easier to send embeds and makes coding commands or things with embeds smoother without having to always forget writing content

### The Ideal Solution

make the default content `[]()` because it looks invisible when sending embeds

### The Current Solution

just `content="[]()"`

**Comment by EnokiUN** [comment]
what no that's dumb I suppose

**Comment by ksIsCute** [comment]
eh
