### ISSUE TITLE
add member models channel_permissions and permissions to the user model

### ISSUE THREAD

**Issue by siqnole** [EnokiUN/voltage#67]
### Summary

add member models channel_permissions and permissions to the user model

### What is the feature request for?

The core library

### The Problem

the `bot.user` is a `user` model but i want to use the `member.channel_permissions` and `member.permissions` attrs so is it possible to use `bot.user` as a member model or just port `member.channel_permissions` and `member.permissions` over to the `user` model?

### The Ideal Solution

so i can check if my bot has permissions to send messages and kick members in channels n stuff so i can make some error handling n stuff yeah and also make some checks

### The Current Solution

sadness

**Comment by EnokiUN** [comment]
`ctx.me` returns the bot's member object for that guild, users don't have permissions so that just won't work, think css think.

**Comment by ksIsCute** [comment]
oh ok thank u i didnt know ctx.me existed pls documentate :trollface:
