### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by Wolfhound905** [EnokiUN/voltage#72]
### Summary

Support python 3.10^

### What is the feature request for?

The core library

### The Problem

Python is now on 3.10 and I don't think there is a good reason this program has to use an older version. My current goal is to run this along side my Discord bot but with the discord library [NAFF](https://github.com/NAFTeam/NAFF/) being 3.10 and this being 3.8, they just don't mix.

### The Ideal Solution

Please just add support for 3.10

**Comment by EnokiUN** [comment]
I am literally using 3.10, what's the issue?

**Comment by Wolfhound905** [comment]
https://app.revolt.chat/server/01FNYD7FYZF1YA4QGEY9PHSK2S/channel/01FYYT0W1HFKD8P001DJ1TRCR7/01G4KV39GMX9FKKAP4SWJZM9KR

**Comment by Wolfhound905** [comment]
ok i am done editing my comment lol

**Comment by EnokiUN** [comment]
that's easily solvable by `pip uninstall voltage && pip install git+https://github.com/EnokiUN/voltage`

**Comment by Wolfhound905** [comment]
Sorry, I think I got it figured out.
