### ISSUE TITLE
errors [SOLVED]

### ISSUE THREAD

**Issue by fily-gif** [EnokiUN/voltage#76]
### Summary

example script doesn't work

### Reproduction Steps

+ have python 3.9
+ do python -m pip install voltage
+ paste example code (from readme.md)
+ run it
+profit

### Minimal Reproducible Code

```python
import voltage
from voltage.ext import commands # Import the commands module from ``voltage.ext``
from config.py import TOKEN

client = commands.CommandsClient("-") # Create a CommandsClient (client that has commands (original ik)) with the prefix set to "-".

@client.listen("ready") # You can still listen to events.
async def ready():
    print("Gaaah, It's rewind time.")

@client.command() # Register a command using the ``command`` decorator.
async def ping(ctx):
    """Sends Pong!""" # Name and description can be passed in the decorator or automatically inferred.
    await ctx.reply("Pong") # Reply to the context's message.

client.run("TOKEN") # Again, replace with your bot token.
```

### Expected Results

bot will run perfectly fine

### Actual Results

Traceback (most recent call last):
  File "/home/andrrwq/code/evry_revolt/main.py", line 1, in <module>
    import voltage
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/__init__.py", line 32, in <module>
    from .client import Client
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/client.py", line 10, in <module>
    from .internals import CacheHandler, HTTPHandler, WebSocketHandler
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/internals/__init__.py", line 7, in <module>
    from .cache import CacheHandler
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/internals/cache.py", line 11, in <module>
    from ..server import Server
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/server.py", line 9, in <module>
    from .invites import Invite
  File "/home/andrrwq/.local/lib/python3.9/site-packages/voltage/invites.py", line 7, in <module>
    from .utils import get
ImportError: cannot import name 'get' from 'voltage.utils' (/home/andrrwq/.local/lib/python3.9/site-packages/voltage/utils/__init__.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

i use ubuntu 22.04LTS and im dumb, so im sorry if the error is stupid

**Comment by EnokiUN** [comment]
that's a relatively known issue, I still have no idea why it happens but the soliton to it is removing voltage then reinstalling it from git (`pip uninstall voltage && pip install -U git+https://github.com/EnokiUN/voltage`)

**Comment by ksIsCute** [comment]
> that's a relatively known issue, I still have no idea why it happens but the solution to it is removing voltage then reinstalling it from git (`pip uninstall voltage && pip install -U git+https://github.com/EnokiUN/voltage`)

this still happens?

**Comment by fily-gif** [comment]
> that's a relatively known issue, I still have no idea why it happens but the soliton to it is removing voltage then reinstalling it from git (`pip uninstall voltage && pip install -U git+https://github.com/EnokiUN/voltage`)

tysm it works now!
