### ISSUE TITLE
AttributeError: cache

### ISSUE THREAD

**Issue by HGStyle** [EnokiUN/voltage#86]
### Summary

I got this error...

### Reproduction Steps

I literaly coded a simple bot.

### Minimal Reproducible Code

```python
import voltage, os
rvl_cli = voltage.Client()
rvl_token = os.getenv('revolt')
rvl_id = 0  # channel id here
rvl_ch = rvl_cli.get_channel(rvl_id)

@rvl_cli.listen('ready')
async def on_rdy():
    print('Revolt bot is ready !')

rvl_cli.run(rvl_token)
```

### Expected Results

The bot run

### Actual Results

I got this error : 
``` 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    rvl_ch = rvl_cli.get_channel(rvl_id)
  File "/home/runner/Discord2Revolt/venv/lib/python3.8/site-packages/voltage/client.py", line 308, in get_channel
    return self.cache.get_channel(channel_id)
AttributeError: cache
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have no idea how to fix that...

**Comment by RGBCube** [comment]
This shouldn't happen, but this us easily fixed by getting the chann after bot start

**Comment by EnokiUN** [comment]
You are *not* supposed to get the channel before the bot is started, do it in the ready event handler
