### ISSUE TITLE
Add Plugins?

### ISSUE THREAD

**Issue by EnokiUN** [EnokiUN/voltage#9]
Add a `voltage.internals.Plugin` that can be inherited from to make plugins to extend the base client's functionality in maybe drastic ways.

Still debating wheather this is even a good idea.

General implementation:

```py
# plugin.py
from voltage.internals import Plugin, plugin_function

class MyPlugin(plugin):
    """
    A very good plugin that does X, Y, Z and adds foo() and bar()
    """
    def __init__(self, word: str):
        self.word = word

    @plugin_function()
    async def foo(self):
        print(self.word)

    @plugin_function()
    async def bar(self, text: str) -> text:
        return text*2

# main.py
import voltage

client = voltage.Client().plug(MyPlugin("Among us"))

client.MyPlugin.foo()

```

example footer :trollface:

**Comment by RGBCube** [comment]
maybe not `client = voltage.Client().Plug(MyPlugin("Among us"))` but 
`client = voltage.Client().plug("name", MyPlugin("Among us"))`

**Comment by EnokiUN** [comment]
> maybe not `client = voltage.Client().Plug(MyPlugin("Among us"))` but `client = voltage.Client().plug("name", MyPlugin("Among us"))`

no that's dumb

**Comment by b1ue64** [comment]
maybe just creating a custom class that inherits from the client and the plugins
like
`class AmogusClient(Client, AmogusPlugin): pass`
thats probably the dumbest idea ever, though

**Comment by EnokiUN** [comment]
at this point why even add them?

**Comment by EnokiUN** [comment]
@RGBCube @b1ue64 petition to not add plugins, they've proved quite useless

**Comment by RGBCube** [comment]
true, just make it an attr of the class

**Comment by RGBCube** [comment]
aka `bot.something = MyPlugin("stuff")`

**Comment by EnokiUN** [comment]
I'd like to hear @b1ue64 's opinion before making a definitive decision, don't close the issue just yet.

**Comment by b1ue64** [comment]
> aka `bot.something = MyPlugin("stuff")`

this seems good
