### ISSUE TITLE
Add more functionality with reactions

### ISSUE THREAD

**Issue by ShadowHedgehog** [EnokiUN/voltage#96]
### Summary

Add more functionality with reactions

### What is the feature request for?

The core library

### The Problem

I want Voltage to be able to do more with reactions. Doing more then just reacting to a message. for example, checking all the members that has reacted to a message however that is rarely anything you can do with Revolt's reactions.

### The Ideal Solution

Add functionality for bots to using reactions like letting us use something like `async for user in new_msg.reactions[0].users():` to see all the members that reacted to the message which would be useful for users that want to make giveaway bots for Revolt in Voltage.

### The Current Solution

There is none, All there is `.react` and nothing else that uses reactions.

### Additional Context

This is what the giveaway command code would look like on discord.py when trying to decide a winner if the Voltage developers need better context.
`new_msg = await ctx.channel.fetch_message(msg.id)
    
users = []
async for user in new_msg.reactions[0].users():
    if user != client.user:
        users.append(user)
            
if winners < 1:
    winners = 1 
if len(users) <= winners:
    selected_winners = users
else:
    selected_winners = random.sample(users, winners)

winners_mention = ", ".join(user.mention for user in selected_winners)
await ctx.send(f"Congratulations {winners_mention}! You won {prize}!")`

**Comment by ksIsCute** [comment]
pls use codeblcoks im begging u

**Comment by EnokiUN** [comment]
I'll have to check what the API actually offers in terms of reaction data and judge what's possible and what we can add!

**Comment by searinminecraft** [comment]
> I'll have to check what the API actually offers in terms of reaction data and judge what's possible and what we can add

When you actually get a message, it also returns the list of reactions:
```json
{
  "_id": "01HHRXZ63H4EQXW0TNZWPQZGJF",
  "nonce": "01HHRXXB8SB3SHS38FE12H39S9",
  "channel": "01H4D54WVAKTB86WRA7PQZ9ETW",
  "author": "01GYKFHP09VY3ZQ4HG4HJ647JY",
  "content": "test message",
  "reactions": {
    "01GE7P61M6KR4HWZSTWXKTGAXB": [
      "01GYKFHP09VY3ZQ4HG4HJ647JY"
    ]
  }
}
```

And the reactions property goes like this:
```json
  "reactions": {
    "<emoji id>": [
      "<user ids>"
    ]
  }
```

**Comment by EnokiUN** [comment]
> > I'll have to check what the API actually offers in terms of reaction data and judge what's possible and what we can add
> 
> When you actually get a message, it also returns the list of reactions:
> 
> ```json
> {
>   "_id": "01HHRXZ63H4EQXW0TNZWPQZGJF",
>   "nonce": "01HHRXXB8SB3SHS38FE12H39S9",
>   "channel": "01H4D54WVAKTB86WRA7PQZ9ETW",
>   "author": "01GYKFHP09VY3ZQ4HG4HJ647JY",
>   "content": "test message",
>   "reactions": {
>     "01GE7P61M6KR4HWZSTWXKTGAXB": [
>       "01GYKFHP09VY3ZQ4HG4HJ647JY"
>     ]
>   }
> }
> ```
> 
> And the reactions property goes like this:
> 
> ```json
>   "reactions": {
>     "<emoji id>": [
>       "<user ids>"
>     ]
>   }
> ```

Assuming that this is the case, would a scope of be just changing `message.interactions.reactions` into a `Option[Dict[Reaction, List[User]]]` to make it more manageable be enough for now?

I am currently focusing on working on another project of mine so I'd like to not waste too much time working on this. If that's alright I can try to administer a provisional PR to make it work.

Additionally if someone is willing to implement the changes themselves or build upon what I'd push I am more than open to.

**Comment by EnokiUN** [comment]
Additional info:

While this model isn't optimal, the way you'd, say, select a random user who reacted to a message for a giveaway would be something along the lines of:

```py
winner = random.choice(message.reactions.get("reaction name / id").values())
```

**Comment by TwistedBonnie** [comment]
> Additional info:
Does this work on the current version of Voltage (0.1.5a8) or do you still have to update it?

**Comment by ShadowHedgehog** [comment]
If the "winner = random.choice(message.reactions.get("reaction name / id").values())" helps get a random user from a list of users that reacted to a certain reaction on a message like used in Giveaway bots and is in Voltage, then that pretty much solves my problem and what I am looking for.

**Comment by EnokiUN** [comment]
Now upon running `pip install -U git+https://github.com/enokiun/voltage` you should be able to find a `message.reactions` field which is a dict of emoji name keys and lists of reacted users which would make
```py
winner = random.choice(message.reactions["reaction name / id"])
```

**Comment by Sharp-Eyes** [comment]
I love voltage

**Comment by searinminecraft** [comment]
Massive W for this one!

**Comment by 2vw** [comment]
is there no event for reactions being added?
